#!/bin/bash
cd /home/opc
wget http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm | tee -a /tmp/wget_log
rpm -ivh mysql-community-release-el7-5.noarch.rpm | tee -a /tmp/rpm_log
yum -y install mysql-server | tee -a /tmp/yum_install_log
service mysqld start
#firewall-cmd --add-port=3306/tcp --permanent  1> /tmp/fw1.log 2>/tmp/fw2.log
#firewall-cmd --reload 1> /tmp/fwr1.log 2>/tmp/fwr2.log

